# Assignment 1

<br> 
    <center>
        <img src="src/A1_ViT_illustration.png" width="300"/>  <img src="src/A1_Earshells_illustration.png" width="300"/>
    </center>
</br>

In the first assignment, you can revise your **general Python skills**. The overall task is to extract information from PDFs in the form of text strings and Pandas DataFrame tables. In particular, you can practice

* installing new libraries and setting up a new environment for your project,
* creating and using **generators** and **decorators**,
* working with **Pandas DataFrames**.

Please provide solutions to all exercises below and send me all notebooks by **28th of June 2026**.

***

## Part I: Setting up a new project environment

In order to reuse tools or libraries shared through, for example, GitHub repositories, you need to be 
at ease with installing new libraries and environments in your own Python setup. 

To this end, the first part of the assignment is to 
* set up Python on your own machine (if you haven't done it yet)
* and install libraries provided in ```src/environment_A1.yml```

You can use the information I shared in my first e-mail on the course details. In particular and **more beginner-friendly**, you can use

1. my YouTube video "[Python Course: Set up Python](https://youtu.be/-RJnYbxVZTg)",
2. my brief instruction on how to set up the [Python environment in Anaconda Navigator](src/A1_Install_environment_in_Anaconda_Navigator.pdf),
3. and switch to the new environment ```A1apml``` and start Jupyterlab in Anaconda Navigator.

If you are **more experienced** and Python as well as Anaconda are already set up, you can

1. install the environment from the console / terminal (Linux / macOS) or Anaconda Prompt (Windows) with the command ```conda env create -f environment_A1.yml``` (you need to do this in the directory ```.../Assignments/src/``` where ```environment_A1.yml``` is stored),
2. activate the environment with ```conda activate A1apml```,
3. and start jupyter lab with ```jupyter lab```.


In other words, you might need to close this Jupyter lab window and restart it from the new environment.

In this notebook, we will **work with this new environment** ```A1apml``` that provides you with
Jupyter lab, NumPy, Pandas, and **PyMuPDF**. 

***

## Part II: Read text from a PDF

In the second part, we want to retrieve some information from the paper
on the influential *vision transformer* (ViT) architecture which is provided in
```data/A1_ViT_paper.pdf```.

For this, we use PyMuPDF which is a high-performance Python library for data extraction, 
analysis, conversion, and manipulation of information stored in PDFs. You will import it through

```Python
import fitz
```

Find more information on the functionalities in this 
[overview](https://pymupdf.readthedocs.io/en/latest/the-basics.html). 

Execute the following cells load data and get a feeling for the library.

In [1]:
import fitz
import pandas as pd
import numpy as np

paper_path = "data/A1_ViT_paper.pdf"

doc = fitz.open(paper_path)

In [2]:
print(f"The paper '{paper_path}' has {len(doc)} pages.")

The paper 'data/A1_ViT_paper.pdf' has 9 pages.

In [3]:
for page_nr, page in enumerate(doc):
    text = page.get_text()
    print(f"----- Page {page_nr+1}\n{text}")

----- Page 1
Published as a conference paper at ICLR 2021
AN IMAGE IS WORTH 16X16 WORDS:
TRANSFORMERS FOR IMAGE RECOGNITION AT SCALE
Alexey Dosovitskiy⇤,†, Lucas Beyer⇤, Alexander Kolesnikov⇤, Dirk Weissenborn⇤,
Xiaohua Zhai⇤, Thomas Unterthiner, Mostafa Dehghani, Matthias Minderer,
Georg Heigold, Sylvain Gelly, Jakob Uszkoreit, Neil Houlsby⇤,†
⇤equal technical contribution, †equal advising
Google Research, Brain Team
{adosovitskiy, neilhoulsby}@google.com
ABSTRACT
While the Transformer architecture has become the de-facto standard for natural
language processing tasks, its applications to computer vision remain limited. In
vision, attention is either applied in conjunction with convolutional networks, or
used to replace certain components of convolutional networks while keeping their
overall structure in place. We show that this reliance on CNNs is not necessary
and a pure transformer applied directly to sequences of image patches can perform
very well on image classiﬁcation tasks. When pre-trained on large amounts of
data and transferred to multiple mid-sized or small image recognition benchmarks
(ImageNet, CIFAR-100, VTAB, etc.), Vision Transformer (ViT) attains excellent
results compared to state-of-the-art convolutional networks while requiring sub-
stantially fewer computational resources to train.1
1
INTRODUCTION
Self-attention-based architectures, in particular Transformers (Vaswani et al., 2017), have become
the model of choice in natural language processing (NLP). The dominant approach is to pre-train on
a large text corpus and then ﬁne-tune on a smaller task-speciﬁc dataset (Devlin et al., 2019). Thanks
to Transformers’ computational efﬁciency and scalability, it has become possible to train models of
unprecedented size, with over 100B parameters (Brown et al., 2020; Lepikhin et al., 2020). With the
models and datasets growing, there is still no sign of saturating performance.
In computer vision, however, convolutional architectures remain dominant (LeCun et al., 1989;
Krizhevsky et al., 2012; He et al., 2016). Inspired by NLP successes, multiple works try combining
CNN-like architectures with self-attention (Wang et al., 2018; Carion et al., 2020), some replacing
the convolutions entirely (Ramachandran et al., 2019; Wang et al., 2020a). The latter models, while
theoretically efﬁcient, have not yet been scaled effectively on modern hardware accelerators due to
the use of specialized attention patterns. Therefore, in large-scale image recognition, classic ResNet-
like architectures are still state of the art (Mahajan et al., 2018; Xie et al., 2020; Kolesnikov et al.,
2020).
Inspired by the Transformer scaling successes in NLP, we experiment with applying a standard
Transformer directly to images, with the fewest possible modiﬁcations. To do so, we split an image
into patches and provide the sequence of linear embeddings of these patches as an input to a Trans-
former. Image patches are treated the same way as tokens (words) in an NLP application. We train
the model on image classiﬁcation in supervised fashion.
When trained on mid-sized datasets such as ImageNet without strong regularization, these mod-
els yield modest accuracies of a few percentage points below ResNets of comparable size. This
seemingly discouraging outcome may be expected: Transformers lack some of the inductive biases
1Fine-tuning
code
and
pre-trained
models
are
available
at
https://github.com/
google-research/vision_transformer
1
arXiv:2010.11929v2  [cs.CV]  3 Jun 2021

----- Page 2
Published as a conference paper at ICLR 2021
inherent to CNNs, such as translation equivariance and locality, and therefore do not generalize well
when trained on insufﬁcient amounts of data.
However, the picture changes if the models are trained on larger datasets (14M-300M images). We
ﬁnd that large scale training trumps inductive bias. Our Vision Transformer (ViT) attains excellent
results when pre-trained at sufﬁcient scale and transferred to tasks with fewer datapoints. When
pre-trained on the public ImageNet-21k dataset or the in-house JFT-300M dataset, ViT approaches
or beats state of the art on multiple image recognition benchmarks. In particular, the best model
reaches the accuracy of 88.55% on ImageNet, 90.72% on ImageNet-ReaL, 94.55% on CIFAR-100,
and 77.63% on the VTAB suite of 19 tasks.
2
RELATED WORK
Transformers were proposed by Vaswani et al. (2017) for machine translation, and have since be-
come the state of the art method in many NLP tasks. Large Transformer-based models are often
pre-trained on large corpora and then ﬁne-tuned for the task at hand: BERT (Devlin et al., 2019)
uses a denoising self-supervised pre-training task, while the GPT line of work uses language mod-
eling as its pre-training task (Radford et al., 2018; 2019; Brown et al., 2020).
Naive application of self-attention to images would require that each pixel attends to every other
pixel. With quadratic cost in the number of pixels, this does not scale to realistic input sizes. Thus,
to apply Transformers in the context of image processing, several approximations have been tried in
the past. Parmar et al. (2018) applied the self-attention only in local neighborhoods for each query
pixel instead of globally. Such local multi-head dot-product self attention blocks can completely
replace convolutions (Hu et al., 2019; Ramachandran et al., 2019; Zhao et al., 2020). In a different
line of work, Sparse Transformers (Child et al., 2019) employ scalable approximations to global self-
attention in order to be applicable to images. An alternative way to scale attention is to apply it in
blocks of varying sizes (Weissenborn et al., 2019), in the extreme case only along individual axes (Ho
et al., 2019; Wang et al., 2020a). Many of these specialized attention architectures demonstrate
promising results on computer vision tasks, but require complex engineering to be implemented
efﬁciently on hardware accelerators.
Most related to ours is the model of Cordonnier et al. (2020), which extracts patches of size 2 ⇥2
from the input image and applies full self-attention on top. This model is very similar to ViT,
but our work goes further to demonstrate that large scale pre-training makes vanilla transformers
competitive with (or even better than) state-of-the-art CNNs. Moreover, Cordonnier et al. (2020)
use a small patch size of 2 ⇥2 pixels, which makes the model applicable only to small-resolution
images, while we handle medium-resolution images as well.
There has also been a lot of interest in combining convolutional neural networks (CNNs) with forms
of self-attention, e.g. by augmenting feature maps for image classiﬁcation (Bello et al., 2019) or by
further processing the output of a CNN using self-attention, e.g. for object detection (Hu et al., 2018;
Carion et al., 2020), video processing (Wang et al., 2018; Sun et al., 2019), image classiﬁcation (Wu
et al., 2020), unsupervised object discovery (Locatello et al., 2020), or uniﬁed text-vision tasks (Chen
et al., 2020c; Lu et al., 2019; Li et al., 2019).
Another recent related model is image GPT (iGPT) (Chen et al., 2020a), which applies Transformers
to image pixels after reducing image resolution and color space. The model is trained in an unsu-
pervised fashion as a generative model, and the resulting representation can then be ﬁne-tuned or
probed linearly for classiﬁcation performance, achieving a maximal accuracy of 72% on ImageNet.
Our work adds to the increasing collection of papers that explore image recognition at larger scales
than the standard ImageNet dataset. The use of additional data sources allows to achieve state-of-
the-art results on standard benchmarks (Mahajan et al., 2018; Touvron et al., 2019; Xie et al., 2020).
Moreover, Sun et al. (2017) study how CNN performance scales with dataset size, and Kolesnikov
et al. (2020); Djolonga et al. (2020) perform an empirical exploration of CNN transfer learning from
large scale datasets such as ImageNet-21k and JFT-300M. We focus on these two latter datasets as
well, but train Transformers instead of ResNet-based models used in prior works.
2

----- Page 3
Published as a conference paper at ICLR 2021
Transformer Encoder
MLP
Head
Vision Transformer (ViT)
*
Linear Projection of Flattened Patches
* Extra learnable
     [ cl ass]  embedding
1
2
3
4
5
6
7
8
9
0
Patch + Position
Embedding
Class
Bird
Ball
Car
...
Embedded
Patches
Multi-Head
Attention
Norm
MLP
Norm
+
L x
+
Transformer Encoder
Figure 1: Model overview. We split an image into ﬁxed-size patches, linearly embed each of them,
add position embeddings, and feed the resulting sequence of vectors to a standard Transformer
encoder. In order to perform classiﬁcation, we use the standard approach of adding an extra learnable
“classiﬁcation token” to the sequence. The illustration of the Transformer encoder was inspired by
Vaswani et al. (2017).
3
METHOD
In model design we follow the original Transformer (Vaswani et al., 2017) as closely as possible.
An advantage of this intentionally simple setup is that scalable NLP Transformer architectures – and
their efﬁcient implementations – can be used almost out of the box.
3.1
VISION TRANSFORMER (VIT)
An overview of the model is depicted in Figure 1. The standard Transformer receives as input a 1D
sequence of token embeddings. To handle 2D images, we reshape the image x 2 RH⇥W ⇥C into a
sequence of ﬂattened 2D patches xp 2 RN⇥(P 2·C), where (H, W) is the resolution of the original
image, C is the number of channels, (P, P) is the resolution of each image patch, and N = HW/P 2
is the resulting number of patches, which also serves as the effective input sequence length for the
Transformer. The Transformer uses constant latent vector size D through all of its layers, so we
ﬂatten the patches and map to D dimensions with a trainable linear projection (Eq. 1). We refer to
the output of this projection as the patch embeddings.
Similar to BERT’s [class] token, we prepend a learnable embedding to the sequence of embed-
ded patches (z0
0 = xclass), whose state at the output of the Transformer encoder (z0
L) serves as the
image representation y (Eq. 4). Both during pre-training and ﬁne-tuning, a classiﬁcation head is at-
tached to z0
L. The classiﬁcation head is implemented by a MLP with one hidden layer at pre-training
time and by a single linear layer at ﬁne-tuning time.
Position embeddings are added to the patch embeddings to retain positional information. We use
standard learnable 1D position embeddings, since we have not observed signiﬁcant performance
gains from using more advanced 2D-aware position embeddings (Appendix D.4). The resulting
sequence of embedding vectors serves as input to the encoder.
The Transformer encoder (Vaswani et al., 2017) consists of alternating layers of multiheaded self-
attention (MSA, see Appendix A) and MLP blocks (Eq. 2, 3). Layernorm (LN) is applied before
every block, and residual connections after every block (Wang et al., 2019; Baevski & Auli, 2019).
3

----- Page 4
Published as a conference paper at ICLR 2021
The MLP contains two layers with a GELU non-linearity.
z0 = [xclass; x1
pE; x2
pE; · · · ; xN
p E] + Epos,
E 2 R(P 2·C)⇥D, Epos 2 R(N+1)⇥D
(1)
z0
` = MSA(LN(z`−1)) + z`−1,
` = 1 . . . L
(2)
z` = MLP(LN(z0
`)) + z0
`,
` = 1 . . . L
(3)
y = LN(z0
L)
(4)
Inductive bias.
We note that Vision Transformer has much less image-speciﬁc inductive bias than
CNNs. In CNNs, locality, two-dimensional neighborhood structure, and translation equivariance are
baked into each layer throughout the whole model. In ViT, only MLP layers are local and transla-
tionally equivariant, while the self-attention layers are global. The two-dimensional neighborhood
structure is used very sparingly: in the beginning of the model by cutting the image into patches and
at ﬁne-tuning time for adjusting the position embeddings for images of different resolution (as de-
scribed below). Other than that, the position embeddings at initialization time carry no information
about the 2D positions of the patches and all spatial relations between the patches have to be learned
from scratch.
Hybrid Architecture.
As an alternative to raw image patches, the input sequence can be formed
from feature maps of a CNN (LeCun et al., 1989). In this hybrid model, the patch embedding
projection E (Eq. 1) is applied to patches extracted from a CNN feature map. As a special case,
the patches can have spatial size 1x1, which means that the input sequence is obtained by simply
ﬂattening the spatial dimensions of the feature map and projecting to the Transformer dimension.
The classiﬁcation input embedding and position embeddings are added as described above.
3.2
FINE-TUNING AND HIGHER RESOLUTION
Typically, we pre-train ViT on large datasets, and ﬁne-tune to (smaller) downstream tasks. For
this, we remove the pre-trained prediction head and attach a zero-initialized D ⇥K feedforward
layer, where K is the number of downstream classes. It is often beneﬁcial to ﬁne-tune at higher
resolution than pre-training (Touvron et al., 2019; Kolesnikov et al., 2020). When feeding images
of higher resolution, we keep the patch size the same, which results in a larger effective sequence
length. The Vision Transformer can handle arbitrary sequence lengths (up to memory constraints),
however, the pre-trained position embeddings may no longer be meaningful. We therefore perform
2D interpolation of the pre-trained position embeddings, according to their location in the original
image. Note that this resolution adjustment and patch extraction are the only points at which an
inductive bias about the 2D structure of the images is manually injected into the Vision Transformer.
4
EXPERIMENTS
We evaluate the representation learning capabilities of ResNet, Vision Transformer (ViT), and the
hybrid. To understand the data requirements of each model, we pre-train on datasets of varying size
and evaluate many benchmark tasks. When considering the computational cost of pre-training the
model, ViT performs very favourably, attaining state of the art on most recognition benchmarks at
a lower pre-training cost. Lastly, we perform a small experiment using self-supervision, and show
that self-supervised ViT holds promise for the future.
4.1
SETUP
Datasets. To explore model scalability, we use the ILSVRC-2012 ImageNet dataset with 1k classes
and 1.3M images (we refer to it as ImageNet in what follows), its superset ImageNet-21k with
21k classes and 14M images (Deng et al., 2009), and JFT (Sun et al., 2017) with 18k classes and
303M high-resolution images. We de-duplicate the pre-training datasets w.r.t. the test sets of the
downstream tasks following Kolesnikov et al. (2020). We transfer the models trained on these
dataset to several benchmark tasks: ImageNet on the original validation labels and the cleaned-up
ReaL labels (Beyer et al., 2020), CIFAR-10/100 (Krizhevsky, 2009), Oxford-IIIT Pets (Parkhi et al.,
2012), and Oxford Flowers-102 (Nilsback & Zisserman, 2008). For these datasets, pre-processing
follows Kolesnikov et al. (2020).
4

----- Page 5
Published as a conference paper at ICLR 2021
Model
Layers
Hidden size D
MLP size
Heads
Params
ViT-Base
12
768
3072
12
86M
ViT-Large
24
1024
4096
16
307M
ViT-Huge
32
1280
5120
16
632M
Table 1: Details of Vision Transformer model variants.
We also evaluate on the 19-task VTAB classiﬁcation suite (Zhai et al., 2019b). VTAB evaluates
low-data transfer to diverse tasks, using 1 000 training examples per task. The tasks are divided into
three groups: Natural – tasks like the above, Pets, CIFAR, etc. Specialized – medical and satellite
imagery, and Structured – tasks that require geometric understanding like localization.
Model Variants. We base ViT conﬁgurations on those used for BERT (Devlin et al., 2019), as
summarized in Table 1. The “Base” and “Large” models are directly adopted from BERT and we
add the larger “Huge” model. In what follows we use brief notation to indicate the model size and
the input patch size: for instance, ViT-L/16 means the “Large” variant with 16⇥16 input patch size.
Note that the Transformer’s sequence length is inversely proportional to the square of the patch size,
thus models with smaller patch size are computationally more expensive.
For the baseline CNNs, we use ResNet (He et al., 2016), but replace the Batch Normalization lay-
ers (Ioffe & Szegedy, 2015) with Group Normalization (Wu & He, 2018), and used standardized
convolutions (Qiao et al., 2019). These modiﬁcations improve transfer (Kolesnikov et al., 2020),
and we denote the modiﬁed model “ResNet (BiT)”. For the hybrids, we feed the intermediate fea-
ture maps into ViT with patch size of one “pixel”. To experiment with different sequence lengths,
we either (i) take the output of stage 4 of a regular ResNet50 or (ii) remove stage 4, place the same
number of layers in stage 3 (keeping the total number of layers), and take the output of this extended
stage 3. Option (ii) results in a 4x longer sequence length, and a more expensive ViT model.
Training & Fine-tuning. We train all models, including ResNets, using Adam (Kingma & Ba,
2015) with β1 = 0.9, β2 = 0.999, a batch size of 4096 and apply a high weight decay of 0.1, which
we found to be useful for transfer of all models (Appendix D.1 shows that, in contrast to common
practices, Adam works slightly better than SGD for ResNets in our setting). We use a linear learning
rate warmup and decay, see Appendix B.1 for details. For ﬁne-tuning we use SGD with momentum,
batch size 512, for all models, see Appendix B.1.1. For ImageNet results in Table 2, we ﬁne-tuned at
higher resolution: 512 for ViT-L/16 and 518 for ViT-H/14, and also used Polyak & Juditsky (1992)
averaging with a factor of 0.9999 (Ramachandran et al., 2019; Wang et al., 2020b).
Metrics. We report results on downstream datasets either through few-shot or ﬁne-tuning accuracy.
Fine-tuning accuracies capture the performance of each model after ﬁne-tuning it on the respective
dataset. Few-shot accuracies are obtained by solving a regularized least-squares regression problem
that maps the (frozen) representation of a subset of training images to {−1, 1}K target vectors. This
formulation allows us to recover the exact solution in closed form. Though we mainly focus on
ﬁne-tuning performance, we sometimes use linear few-shot accuracies for fast on-the-ﬂy evaluation
where ﬁne-tuning would be too costly.
4.2
COMPARISON TO STATE OF THE ART
We ﬁrst compare our largest models – ViT-H/14 and ViT-L/16 – to state-of-the-art CNNs from
the literature. The ﬁrst comparison point is Big Transfer (BiT) (Kolesnikov et al., 2020), which
performs supervised transfer learning with large ResNets. The second is Noisy Student (Xie et al.,
2020), which is a large EfﬁcientNet trained using semi-supervised learning on ImageNet and JFT-
300M with the labels removed. Currently, Noisy Student is the state of the art on ImageNet and
BiT-L on the other datasets reported here. All models were trained on TPUv3 hardware, and we
report the number of TPUv3-core-days taken to pre-train each of them, that is, the number of TPU
v3 cores (2 per chip) used for training multiplied by the training time in days.
Table 2 shows the results. The smaller ViT-L/16 model pre-trained on JFT-300M outperforms BiT-L
(which is pre-trained on the same dataset) on all tasks, while requiring substantially less computa-
tional resources to train. The larger model, ViT-H/14, further improves the performance, especially
on the more challenging datasets – ImageNet, CIFAR-100, and the VTAB suite. Interestingly, this
5

----- Page 6
Published as a conference paper at ICLR 2021
Ours-JFT
Ours-JFT
Ours-I21k
BiT-L
Noisy Student
(ViT-H/14)
(ViT-L/16)
(ViT-L/16)
(ResNet152x4)
(EfﬁcientNet-L2)
ImageNet
88.55 ± 0.04
87.76 ± 0.03
85.30 ± 0.02
87.54 ± 0.02
88.4/88.5⇤
ImageNet ReaL
90.72 ± 0.05
90.54 ± 0.03
88.62 ± 0.05
90.54
90.55
CIFAR-10
99.50 ± 0.06
99.42 ± 0.03
99.15 ± 0.03
99.37 ± 0.06

### Exercise II.1
Write a **generator** ```page_provider``` which provides the pages of the PDF as strings.
The generator is supposed to expect the path to the PDF ```paper_path```
as an argument and, when, for example, used in a loop, provide the next page of
the document.

Fill in the cell below:

In [4]:
# Exercise II.1
# Goal: create a generator called page_provider.
# A generator is a function that uses yield instead of return.
# In Notebook 2, squared_sequence yielded one number at a time.
# Here we use the same idea, but yield one PDF page text at a time.
def page_provider(paper_path):
    # Open the PDF file.
    # fitz.open(...) gives us a document object that we can loop over.
    doc = fitz.open(paper_path)

    # Go through the document page by page.
    # On each loop step, page is one PDF page object.
    for page in doc:
        # Extract the visible text from the current PDF page.
        page_text = page.get_text()

        # yield sends this page text back to the user of the generator.
        # The function pauses here until the next page is requested.
        yield page_text

    # Close the document after all pages were provided.
    doc.close()


# Small check: use the generator in a for-loop.
# This prints the pages one after another, just like the example above.
for page_text in page_provider(paper_path):
    print(page_text)

Published as a conference paper at ICLR 2021
AN IMAGE IS WORTH 16X16 WORDS:
TRANSFORMERS FOR IMAGE RECOGNITION AT SCALE
Alexey Dosovitskiy⇤,†, Lucas Beyer⇤, Alexander Kolesnikov⇤, Dirk Weissenborn⇤,
Xiaohua Zhai⇤, Thomas Unterthiner, Mostafa Dehghani, Matthias Minderer,
Georg Heigold, Sylvain Gelly, Jakob Uszkoreit, Neil Houlsby⇤,†
⇤equal technical contribution, †equal advising
Google Research, Brain Team
{adosovitskiy, neilhoulsby}@google.com
ABSTRACT
While the Transformer architecture has become the de-facto standard for natural
language processing tasks, its applications to computer vision remain limited. In
vision, attention is either applied in conjunction with convolutional networks, or
used to replace certain components of convolutional networks while keeping their
overall structure in place. We show that this reliance on CNNs is not necessary
and a pure transformer applied directly to sequences of image patches can perform
very well on image classiﬁcation tasks. When pre-trained on large amounts of
data and transferred to multiple mid-sized or small image recognition benchmarks
(ImageNet, CIFAR-100, VTAB, etc.), Vision Transformer (ViT) attains excellent
results compared to state-of-the-art convolutional networks while requiring sub-
stantially fewer computational resources to train.1
1
INTRODUCTION
Self-attention-based architectures, in particular Transformers (Vaswani et al., 2017), have become
the model of choice in natural language processing (NLP). The dominant approach is to pre-train on
a large text corpus and then ﬁne-tune on a smaller task-speciﬁc dataset (Devlin et al., 2019). Thanks
to Transformers’ computational efﬁciency and scalability, it has become possible to train models of
unprecedented size, with over 100B parameters (Brown et al., 2020; Lepikhin et al., 2020). With the
models and datasets growing, there is still no sign of saturating performance.
In computer vision, however, convolutional architectures remain dominant (LeCun et al., 1989;
Krizhevsky et al., 2012; He et al., 2016). Inspired by NLP successes, multiple works try combining
CNN-like architectures with self-attention (Wang et al., 2018; Carion et al., 2020), some replacing
the convolutions entirely (Ramachandran et al., 2019; Wang et al., 2020a). The latter models, while
theoretically efﬁcient, have not yet been scaled effectively on modern hardware accelerators due to
the use of specialized attention patterns. Therefore, in large-scale image recognition, classic ResNet-
like architectures are still state of the art (Mahajan et al., 2018; Xie et al., 2020; Kolesnikov et al.,
2020).
Inspired by the Transformer scaling successes in NLP, we experiment with applying a standard
Transformer directly to images, with the fewest possible modiﬁcations. To do so, we split an image
into patches and provide the sequence of linear embeddings of these patches as an input to a Trans-
former. Image patches are treated the same way as tokens (words) in an NLP application. We train
the model on image classiﬁcation in supervised fashion.
When trained on mid-sized datasets such as ImageNet without strong regularization, these mod-
els yield modest accuracies of a few percentage points below ResNets of comparable size. This
seemingly discouraging outcome may be expected: Transformers lack some of the inductive biases
1Fine-tuning
code
and
pre-trained
models
are
available
at
https://github.com/
google-research/vision_transformer
1
arXiv:2010.11929v2  [cs.CV]  3 Jun 2021

Published as a conference paper at ICLR 2021
inherent to CNNs, such as translation equivariance and locality, and therefore do not generalize well
when trained on insufﬁcient amounts of data.
However, the picture changes if the models are trained on larger datasets (14M-300M images). We
ﬁnd that large scale training trumps inductive bias. Our Vision Transformer (ViT) attains excellent
results when pre-trained at sufﬁcient scale and transferred to tasks with fewer datapoints. When
pre-trained on the public ImageNet-21k dataset or the in-house JFT-300M dataset, ViT approaches
or beats state of the art on multiple image recognition benchmarks. In particular, the best model
reaches the accuracy of 88.55% on ImageNet, 90.72% on ImageNet-ReaL, 94.55% on CIFAR-100,
and 77.63% on the VTAB suite of 19 tasks.
2
RELATED WORK
Transformers were proposed by Vaswani et al. (2017) for machine translation, and have since be-
come the state of the art method in many NLP tasks. Large Transformer-based models are often
pre-trained on large corpora and then ﬁne-tuned for the task at hand: BERT (Devlin et al., 2019)
uses a denoising self-supervised pre-training task, while the GPT line of work uses language mod-
eling as its pre-training task (Radford et al., 2018; 2019; Brown et al., 2020).
Naive application of self-attention to images would require that each pixel attends to every other
pixel. With quadratic cost in the number of pixels, this does not scale to realistic input sizes. Thus,
to apply Transformers in the context of image processing, several approximations have been tried in
the past. Parmar et al. (2018) applied the self-attention only in local neighborhoods for each query
pixel instead of globally. Such local multi-head dot-product self attention blocks can completely
replace convolutions (Hu et al., 2019; Ramachandran et al., 2019; Zhao et al., 2020). In a different
line of work, Sparse Transformers (Child et al., 2019) employ scalable approximations to global self-
attention in order to be applicable to images. An alternative way to scale attention is to apply it in
blocks of varying sizes (Weissenborn et al., 2019), in the extreme case only along individual axes (Ho
et al., 2019; Wang et al., 2020a). Many of these specialized attention architectures demonstrate
promising results on computer vision tasks, but require complex engineering to be implemented
efﬁciently on hardware accelerators.
Most related to ours is the model of Cordonnier et al. (2020), which extracts patches of size 2 ⇥2
from the input image and applies full self-attention on top. This model is very similar to ViT,
but our work goes further to demonstrate that large scale pre-training makes vanilla transformers
competitive with (or even better than) state-of-the-art CNNs. Moreover, Cordonnier et al. (2020)
use a small patch size of 2 ⇥2 pixels, which makes the model applicable only to small-resolution
images, while we handle medium-resolution images as well.
There has also been a lot of interest in combining convolutional neural networks (CNNs) with forms
of self-attention, e.g. by augmenting feature maps for image classiﬁcation (Bello et al., 2019) or by
further processing the output of a CNN using self-attention, e.g. for object detection (Hu et al., 2018;
Carion et al., 2020), video processing (Wang et al., 2018; Sun et al., 2019), image classiﬁcation (Wu
et al., 2020), unsupervised object discovery (Locatello et al., 2020), or uniﬁed text-vision tasks (Chen
et al., 2020c; Lu et al., 2019; Li et al., 2019).
Another recent related model is image GPT (iGPT) (Chen et al., 2020a), which applies Transformers
to image pixels after reducing image resolution and color space. The model is trained in an unsu-
pervised fashion as a generative model, and the resulting representation can then be ﬁne-tuned or
probed linearly for classiﬁcation performance, achieving a maximal accuracy of 72% on ImageNet.
Our work adds to the increasing collection of papers that explore image recognition at larger scales
than the standard ImageNet dataset. The use of additional data sources allows to achieve state-of-
the-art results on standard benchmarks (Mahajan et al., 2018; Touvron et al., 2019; Xie et al., 2020).
Moreover, Sun et al. (2017) study how CNN performance scales with dataset size, and Kolesnikov
et al. (2020); Djolonga et al. (2020) perform an empirical exploration of CNN transfer learning from
large scale datasets such as ImageNet-21k and JFT-300M. We focus on these two latter datasets as
well, but train Transformers instead of ResNet-based models used in prior works.
2

Published as a conference paper at ICLR 2021
Transformer Encoder
MLP
Head
Vision Transformer (ViT)
*
Linear Projection of Flattened Patches
* Extra learnable
     [ cl ass]  embedding
1
2
3
4
5
6
7
8
9
0
Patch + Position
Embedding
Class
Bird
Ball
Car
...
Embedded
Patches
Multi-Head
Attention
Norm
MLP
Norm
+
L x
+
Transformer Encoder
Figure 1: Model overview. We split an image into ﬁxed-size patches, linearly embed each of them,
add position embeddings, and feed the resulting sequence of vectors to a standard Transformer
encoder. In order to perform classiﬁcation, we use the standard approach of adding an extra learnable
“classiﬁcation token” to the sequence. The illustration of the Transformer encoder was inspired by
Vaswani et al. (2017).
3
METHOD
In model design we follow the original Transformer (Vaswani et al., 2017) as closely as possible.
An advantage of this intentionally simple setup is that scalable NLP Transformer architectures – and
their efﬁcient implementations – can be used almost out of the box.
3.1
VISION TRANSFORMER (VIT)
An overview of the model is depicted in Figure 1. The standard Transformer receives as input a 1D
sequence of token embeddings. To handle 2D images, we reshape the image x 2 RH⇥W ⇥C into a
sequence of ﬂattened 2D patches xp 2 RN⇥(P 2·C), where (H, W) is the resolution of the original
image, C is the number of channels, (P, P) is the resolution of each image patch, and N = HW/P 2
is the resulting number of patches, which also serves as the effective input sequence length for the
Transformer. The Transformer uses constant latent vector size D through all of its layers, so we
ﬂatten the patches and map to D dimensions with a trainable linear projection (Eq. 1). We refer to
the output of this projection as the patch embeddings.
Similar to BERT’s [class] token, we prepend a learnable embedding to the sequence of embed-
ded patches (z0
0 = xclass), whose state at the output of the Transformer encoder (z0
L) serves as the
image representation y (Eq. 4). Both during pre-training and ﬁne-tuning, a classiﬁcation head is at-
tached to z0
L. The classiﬁcation head is implemented by a MLP with one hidden layer at pre-training
time and by a single linear layer at ﬁne-tuning time.
Position embeddings are added to the patch embeddings to retain positional information. We use
standard learnable 1D position embeddings, since we have not observed signiﬁcant performance
gains from using more advanced 2D-aware position embeddings (Appendix D.4). The resulting
sequence of embedding vectors serves as input to the encoder.
The Transformer encoder (Vaswani et al., 2017) consists of alternating layers of multiheaded self-
attention (MSA, see Appendix A) and MLP blocks (Eq. 2, 3). Layernorm (LN) is applied before
every block, and residual connections after every block (Wang et al., 2019; Baevski & Auli, 2019).
3

Published as a conference paper at ICLR 2021
The MLP contains two layers with a GELU non-linearity.
z0 = [xclass; x1
pE; x2
pE; · · · ; xN
p E] + Epos,
E 2 R(P 2·C)⇥D, Epos 2 R(N+1)⇥D
(1)
z0
` = MSA(LN(z`−1)) + z`−1,
` = 1 . . . L
(2)
z` = MLP(LN(z0
`)) + z0
`,
` = 1 . . . L
(3)
y = LN(z0
L)
(4)
Inductive bias.
We note that Vision Transformer has much less image-speciﬁc inductive bias than
CNNs. In CNNs, locality, two-dimensional neighborhood structure, and translation equivariance are
baked into each layer throughout the whole model. In ViT, only MLP layers are local and transla-
tionally equivariant, while the self-attention layers are global. The two-dimensional neighborhood
structure is used very sparingly: in the beginning of the model by cutting the image into patches and
at ﬁne-tuning time for adjusting the position embeddings for images of different resolution (as de-
scribed below). Other than that, the position embeddings at initialization time carry no information
about the 2D positions of the patches and all spatial relations between the patches have to be learned
from scratch.
Hybrid Architecture.
As an alternative to raw image patches, the input sequence can be formed
from feature maps of a CNN (LeCun et al., 1989). In this hybrid model, the patch embedding
projection E (Eq. 1) is applied to patches extracted from a CNN feature map. As a special case,
the patches can have spatial size 1x1, which means that the input sequence is obtained by simply
ﬂattening the spatial dimensions of the feature map and projecting to the Transformer dimension.
The classiﬁcation input embedding and position embeddings are added as described above.
3.2
FINE-TUNING AND HIGHER RESOLUTION
Typically, we pre-train ViT on large datasets, and ﬁne-tune to (smaller) downstream tasks. For
this, we remove the pre-trained prediction head and attach a zero-initialized D ⇥K feedforward
layer, where K is the number of downstream classes. It is often beneﬁcial to ﬁne-tune at higher
resolution than pre-training (Touvron et al., 2019; Kolesnikov et al., 2020). When feeding images
of higher resolution, we keep the patch size the same, which results in a larger effective sequence
length. The Vision Transformer can handle arbitrary sequence lengths (up to memory constraints),
however, the pre-trained position embeddings may no longer be meaningful. We therefore perform
2D interpolation of the pre-trained position embeddings, according to their location in the original
image. Note that this resolution adjustment and patch extraction are the only points at which an
inductive bias about the 2D structure of the images is manually injected into the Vision Transformer.
4
EXPERIMENTS
We evaluate the representation learning capabilities of ResNet, Vision Transformer (ViT), and the
hybrid. To understand the data requirements of each model, we pre-train on datasets of varying size
and evaluate many benchmark tasks. When considering the computational cost of pre-training the
model, ViT performs very favourably, attaining state of the art on most recognition benchmarks at
a lower pre-training cost. Lastly, we perform a small experiment using self-supervision, and show
that self-supervised ViT holds promise for the future.
4.1
SETUP
Datasets. To explore model scalability, we use the ILSVRC-2012 ImageNet dataset with 1k classes
and 1.3M images (we refer to it as ImageNet in what follows), its superset ImageNet-21k with
21k classes and 14M images (Deng et al., 2009), and JFT (Sun et al., 2017) with 18k classes and
303M high-resolution images. We de-duplicate the pre-training datasets w.r.t. the test sets of the
downstream tasks following Kolesnikov et al. (2020). We transfer the models trained on these
dataset to several benchmark tasks: ImageNet on the original validation labels and the cleaned-up
ReaL labels (Beyer et al., 2020), CIFAR-10/100 (Krizhevsky, 2009), Oxford-IIIT Pets (Parkhi et al.,
2012), and Oxford Flowers-102 (Nilsback & Zisserman, 2008). For these datasets, pre-processing
follows Kolesnikov et al. (2020).
4

Published as a conference paper at ICLR 2021
Model
Layers
Hidden size D
MLP size
Heads
Params
ViT-Base
12
768
3072
12
86M
ViT-Large
24
1024
4096
16
307M
ViT-Huge
32
1280
5120
16
632M
Table 1: Details of Vision Transformer model variants.
We also evaluate on the 19-task VTAB classiﬁcation suite (Zhai et al., 2019b). VTAB evaluates
low-data transfer to diverse tasks, using 1 000 training examples per task. The tasks are divided into
three groups: Natural – tasks like the above, Pets, CIFAR, etc. Specialized – medical and satellite
imagery, and Structured – tasks that require geometric understanding like localization.
Model Variants. We base ViT conﬁgurations on those used for BERT (Devlin et al., 2019), as
summarized in Table 1. The “Base” and “Large” models are directly adopted from BERT and we
add the larger “Huge” model. In what follows we use brief notation to indicate the model size and
the input patch size: for instance, ViT-L/16 means the “Large” variant with 16⇥16 input patch size.
Note that the Transformer’s sequence length is inversely proportional to the square of the patch size,
thus models with smaller patch size are computationally more expensive.
For the baseline CNNs, we use ResNet (He et al., 2016), but replace the Batch Normalization lay-
ers (Ioffe & Szegedy, 2015) with Group Normalization (Wu & He, 2018), and used standardized
convolutions (Qiao et al., 2019). These modiﬁcations improve transfer (Kolesnikov et al., 2020),
and we denote the modiﬁed model “ResNet (BiT)”. For the hybrids, we feed the intermediate fea-
ture maps into ViT with patch size of one “pixel”. To experiment with different sequence lengths,
we either (i) take the output of stage 4 of a regular ResNet50 or (ii) remove stage 4, place the same
number of layers in stage 3 (keeping the total number of layers), and take the output of this extended
stage 3. Option (ii) results in a 4x longer sequence length, and a more expensive ViT model.
Training & Fine-tuning. We train all models, including ResNets, using Adam (Kingma & Ba,
2015) with β1 = 0.9, β2 = 0.999, a batch size of 4096 and apply a high weight decay of 0.1, which
we found to be useful for transfer of all models (Appendix D.1 shows that, in contrast to common
practices, Adam works slightly better than SGD for ResNets in our setting). We use a linear learning
rate warmup and decay, see Appendix B.1 for details. For ﬁne-tuning we use SGD with momentum,
batch size 512, for all models, see Appendix B.1.1. For ImageNet results in Table 2, we ﬁne-tuned at
higher resolution: 512 for ViT-L/16 and 518 for ViT-H/14, and also used Polyak & Juditsky (1992)
averaging with a factor of 0.9999 (Ramachandran et al., 2019; Wang et al., 2020b).
Metrics. We report results on downstream datasets either through few-shot or ﬁne-tuning accuracy.
Fine-tuning accuracies capture the performance of each model after ﬁne-tuning it on the respective
dataset. Few-shot accuracies are obtained by solving a regularized least-squares regression problem
that maps the (frozen) representation of a subset of training images to {−1, 1}K target vectors. This
formulation allows us to recover the exact solution in closed form. Though we mainly focus on
ﬁne-tuning performance, we sometimes use linear few-shot accuracies for fast on-the-ﬂy evaluation
where ﬁne-tuning would be too costly.
4.2
COMPARISON TO STATE OF THE ART
We ﬁrst compare our largest models – ViT-H/14 and ViT-L/16 – to state-of-the-art CNNs from
the literature. The ﬁrst comparison point is Big Transfer (BiT) (Kolesnikov et al., 2020), which
performs supervised transfer learning with large ResNets. The second is Noisy Student (Xie et al.,
2020), which is a large EfﬁcientNet trained using semi-supervised learning on ImageNet and JFT-
300M with the labels removed. Currently, Noisy Student is the state of the art on ImageNet and
BiT-L on the other datasets reported here. All models were trained on TPUv3 hardware, and we
report the number of TPUv3-core-days taken to pre-train each of them, that is, the number of TPU
v3 cores (2 per chip) used for training multiplied by the training time in days.
Table 2 shows the results. The smaller ViT-L/16 model pre-trained on JFT-300M outperforms BiT-L
(which is pre-trained on the same dataset) on all tasks, while requiring substantially less computa-
tional resources to train. The larger model, ViT-H/14, further improves the performance, especially
on the more challenging datasets – ImageNet, CIFAR-100, and the VTAB suite. Interestingly, this
5

Published as a conference paper at ICLR 2021
Ours-JFT
Ours-JFT
Ours-I21k
BiT-L
Noisy Student
(ViT-H/14)
(ViT-L/16)
(ViT-L/16)
(ResNet152x4)
(EfﬁcientNet-L2)
ImageNet
88.55 ± 0.04
87.76 ± 0.03
85.30 ± 0.02
87.54 ± 0.02
88.4/88.5⇤
ImageNet ReaL
90.72 ± 0.05
90.54 ± 0.03
88.62 ± 0.05
90.54
90.55
CIFAR-10
99.50 ± 0.06
99.42 ± 0.03
99.15 ± 0.03
99.37 ± 0.06
−
CIFAR-100
94.55 ± 0.04
93.90 ± 0.05
93.25 ± 0.05
93.51 ± 0.08
−

### Exercise II.2
Extract the abstract and conclusion sections from the PDF into a string variable.

For this, assign the generator ```page_provider``` to a variable e.g. ```get_page```. Loop over the pages and extract the sections on 'ABSTRACT'
and 'CONCLUSION' and store the text in one string variable ```result_text```.

Ideas on strings provided in [Notebook 2](../Notebooks/2-Python_Concepts.ipynb) might help you with that.

Fill in the cell below:

In [5]:
# Exercise II.2
# Goal: collect the ABSTRACT and CONCLUSION sections in one string.

# Create the generator object.
# No pages are read yet; this only prepares the generator.
get_page = page_provider(paper_path)

# Start with an empty string.
# We will add the abstract and conclusion to this variable.
result_text = ""

# Loop over all page strings from the generator.
for page_text in get_page:

    # Check whether the current page contains the abstract heading.
    if "ABSTRACT" in page_text:
        # split("ABSTRACT") cuts the text into the part before and after ABSTRACT.
        # [1] keeps the part after ABSTRACT.
        text_after_abstract = page_text.split("ABSTRACT")[1]

        # The abstract ends before the INTRODUCTION heading.
        # Splitting again lets us keep only the abstract paragraph.
        abstract_text = text_after_abstract.split("INTRODUCTION")[0]

        # Add a label and the extracted text to the final result string.
        result_text += "ABSTRACT\n"
        result_text += abstract_text.strip()
        result_text += "\n\n"

    # Check whether the current page contains the conclusion heading.
    if "CONCLUSION" in page_text:
        # Keep the text after the CONCLUSION heading.
        text_after_conclusion = page_text.split("CONCLUSION")[1]

        # In this paper, the conclusion ends before REFERENCES.
        conclusion_text = text_after_conclusion.split("REFERENCES")[0]

        # Add a label and the extracted conclusion to the same result string.
        result_text += "CONCLUSION\n"
        result_text += conclusion_text.strip()

In [6]:
print(result_text)

ABSTRACT
While the Transformer architecture has become the de-facto standard for natural
language processing tasks, its applications to computer vision remain limited. In
vision, attention is either applied in conjunction with convolutional networks, or
used to replace certain components of convolutional networks while keeping their
overall structure in place. We show that this reliance on CNNs is not necessary
and a pure transformer applied directly to sequences of image patches can perform
very well on image classiﬁcation tasks. When pre-trained on large amounts of
data and transferred to multiple mid-sized or small image recognition benchmarks
(ImageNet, CIFAR-100, VTAB, etc.), Vision Transformer (ViT) attains excellent
results compared to state-of-the-art convolutional networks while requiring sub-
stantially fewer computational resources to train.1
1

CONCLUSION
We have explored the direct application of Transformers to image recognition. Unlike prior works
using self-attention in computer vision, we do not introduce image-speciﬁc inductive biases into
the architecture apart from the initial patch extraction step. Instead, we interpret an image as a
sequence of patches and process it by a standard Transformer encoder as used in NLP. This simple,
yet scalable, strategy works surprisingly well when coupled with pre-training on large datasets.
Thus, Vision Transformer matches or exceeds the state of the art on many image classiﬁcation
datasets, whilst being relatively cheap to pre-train.
While these initial results are encouraging, many challenges remain. One is to apply ViT to other
computer vision tasks, such as detection and segmentation. Our results, coupled with those in Carion
et al. (2020), indicate the promise of this approach. Another challenge is to continue exploring self-
supervised pre-training methods. Our initial experiments show improvement from self-supervised
pre-training, but there is still large gap between self-supervised and large-scale supervised pre-
training. Finally, further scaling of ViT would likely lead to improved performance.
ACKNOWLEDGEMENTS
The work was performed in Berlin, Z¨urich, and Amsterdam. We thank many colleagues at Google
for their help, in particular Andreas Steiner for crucial help with the infrastructure and the open-
source release of the code; Joan Puigcerver and Maxim Neumann for help with the large-scale
training infrastructure; Dmitry Lepikhin, Aravindh Mahendran, Daniel Keysers, Mario Luˇci´c, Noam
Shazeer, Ashish Vaswani, and Colin Raffel for useful discussions.

***

## Part III: Read a table from a PDF

In the third part, we tackle the slightly more challenging task of extracting 
tables from PDFs. We use the exemplary table in ```data/A1_table_example.pdf``` for this.

The following cell provide a wrapper function ```get_pandas_df``` to load the first table 
occurring on a specified page into a Pandas DataFrame. You can ignore the arguments
```search_strategy```and ```search_region```for now. Read up on the used ```PyMuPDF``` function 
in the [find_tables documentation](https://pymupdf.readthedocs.io/en/latest/page.html#Page.find_tables).

In [7]:
import fitz
import pandas as pd
import numpy as np


def get_pandas_df(page, search_strategy="text", search_region=None):
    tabs = page.find_tables(strategy=search_strategy, clip=search_region)

    tab = tabs[0]
    df = tab.to_pandas()

    df = df.convert_dtypes()

    return df

In [8]:
paper_path = "data/A1_table_example.pdf"

doc = fitz.open(paper_path)

print(f"The paper '{paper_path}' has {len(doc)} pages.")

table_df = get_pandas_df(doc[0])

The paper 'data/A1_table_example.pdf' has 1 pages.
Consider using the pymupdf_layout package for a greatly improved page layout analysis.

In [9]:
table_df

,Subset,Sex,Length,Diameter,Height,WholeW.,ShuckedW.,VisceraW.,ShellW.,Rings,Price
0,,,,,,,,,,,
1,train,I,0.350,0.260,0.075,0.180,0.090,0.025,0.055,5.0,1.206
2,train,F,0.545,0.440,0.135,0.918,0.429,0.202,0.238,10.0,18.403
3,test,F,0.650,0.545,0.175,1.524,0.590,0.326,0.496,10.0,31.456
4,train,I,0.500,0.395,0.141,0.621,0.292,0.120,0.195,9.0,5.648
5,train,I,0.439,0.335,0.110,0.389,0.175,0.083,0.111,7.0,1.967
6,train,I,0.295,0.220,0.085,0.129,0.058,0.027,0.037,5.0,0.229
7,train,I,0.475,0.365,0.120,0.519,0.268,0.109,0.137,8.0,4.143
8,train,M,0.550,0.451,0.149,1.014,0.408,0.202,0.287,10.0,16.212
9,train,I,0.465,0.355,0.119,0.581,0.255,0.092,0.184,8.0,7.456
10,test,I,0.380,0.290,0.100,0.237,0.108,0.040,0.082,6.0,2.285
11,train,F,0.619,0.475,0.175,1.017,0.436,0.214,0.325,10.0,20.275
12,train,I,0.510,0.399,0.125,0.593,0.239,0.130,0.204,8.0,6.862
13,train,I,0.495,0.381,0.130,0.513,0.218,0.116,0.160,7.0,5.506
14,test,I,0.485,0.390,0.125,0.591,0.287,0.141,0.120,9.0,6.302
15,train,I,0.499,0.380,0.110,0.562,0.280,0.107,0.150,9.0,5.090
16,test,I,0.405,0.310,0.110,0.911,0.416,0.208,0.099,8.0,8.616
17,test,F,0.575,0.470,0.155,1.116,0.510,0.239,0.339,10.0,22.109
18,train,M,0.695,0.549,0.195,1.664,0.727,0.359,0.445,11.0,24.599
19,train,F,0.555,0.430,0.136,0.812,0.405,0.164,0.222,9.0,16.362
20,test,F,0.550,0.425,0.145,0.797,0.297,0.150,0.265,9.0,14.634
21,train,M,0.549,0.421,0.161,1.340,0.633,0.311,0.344,10.0,20.974
22,train,F,0.715,0.524,0.185,1.560,0.665,0.383,0.405,11.0,32.519
23,train,F,0.575,0.475,0.160,0.895,0.360,0.220,0.272,9.0,16.902
24,,,,,,,,,,,
25,,,,,Table 1:,Earshells da,ta example.,,,,

### Exercise III.1

As you probably have noticed ```table_df``` requires some addtional processing
before being properly used as DataFrame.

Thus, write a **decorator** ```nicer_df``` which can be used to conveniently extend
the functionality of our ```get_pandas_df```. In particular, please do not change the ```get_pandas_df``` function, but define a decorator as discussed in [Notebook 2](../Notebooks/2-Python_Concepts.ipynb).

Complete the cell below and perform the following steps:

* Drop all rows where entries with only empty strings ```''``` make up at least half of the entries in that row 
* Convert columns with numeric values to floats or integers, respectively
* for each numeric row, provide as the last two rows the mean and standard deviation

Hints: Your solution could include the following parts

*  ```== ''```
*  ```.sum(axis=1)```
*  ```~``` operator for negation, i.e. ```~np.array([True, True, False])``` becomes ```array([False, False,  True])```
*  ```pd.to_numeric(..., errors='ignore')```
*  ```df.loc[row_index, column_name]```

Note that your own solution might not require all of these.

In [10]:
# Exercise III.1
# Goal: write a decorator that improves the DataFrame returned by get_pandas_df.
# A decorator is a function that receives another function as input.
def nicer_df(func):

    # wrapper will replace the original function after decoration.
    # *args and **kwargs allow us to pass on all arguments unchanged.
    def wrapper(*args, **kwargs):

        # First run the original function.
        # For this assignment, func is get_pandas_df.
        df = func(*args, **kwargs)

        # Make a copy before cleaning.
        # This keeps the original returned DataFrame separate from our edits.
        df = df.copy()

        # Part 1: remove rows that are mostly empty strings.
        # (df == "") creates a True/False table.
        # True means that this entry is an empty string.
        empty_string_table = df == ""

        # Sum the True values in each row.
        # In Python, True behaves like 1 and False behaves like 0.
        empty_entries_per_row = empty_string_table.sum(axis=1)

        # A row should be dropped if at least half of its entries are empty.
        half_number_of_columns = len(df.columns) / 2
        rows_to_drop = empty_entries_per_row >= half_number_of_columns

        # Keep the opposite of rows_to_drop.
        # The ~ operator changes True to False and False to True.
        df = df[~rows_to_drop]

        # Part 2: convert columns to numbers where possible.
        # Some columns contain text, for example train/test or sex.
        # Those columns cannot be converted and are left unchanged.
        for column in df.columns:
            try:
                df[column] = pd.to_numeric(df[column])
            except ValueError:
                # If conversion fails, keep this column as it is.
                pass

        # Part 3: add mean and standard deviation for numeric columns.
        # select_dtypes keeps only columns with numeric values.
        numeric_columns = df.select_dtypes(include=[np.number]).columns

        # Add the mean values in a new last row called "Mean".
        df.loc["Mean", numeric_columns] = df[numeric_columns].mean()

        # Add the standard deviations in another last row called "Std".
        df.loc["Std", numeric_columns] = df[numeric_columns].std()

        # Return the cleaned and extended DataFrame.
        return df

    # Return the wrapper function, not the result of wrapper.
    return wrapper

If you were successful with performing all the outlined steps,
you can *decorate* the ```get_pandas_df``` like this:

In [11]:
@nicer_df
def get_pandas_df(page, search_strategy="text", search_region=None):
    tabs = page.find_tables(strategy=search_strategy, clip=search_region)

    tab = tabs[0]
    df = tab.to_pandas()

    df = df.convert_dtypes()

    return df

Re-run the table extraction with the extended functionality:

In [12]:
import fitz
import pandas as pd
import numpy as np

paper_path = "data/A1_table_example.pdf"

doc = fitz.open(paper_path)

print(f"The paper '{paper_path}' has {len(doc)} pages.")

nicer_table_df = get_pandas_df(doc[0])

The paper 'data/A1_table_example.pdf' has 1 pages.

Here is a comparison between the "old" ```table_df```
and "new" ```nicer_table_df```

In [13]:
table_df

,Subset,Sex,Length,Diameter,Height,WholeW.,ShuckedW.,VisceraW.,ShellW.,Rings,Price
0,,,,,,,,,,,
1,train,I,0.350,0.260,0.075,0.180,0.090,0.025,0.055,5.0,1.206
2,train,F,0.545,0.440,0.135,0.918,0.429,0.202,0.238,10.0,18.403
3,test,F,0.650,0.545,0.175,1.524,0.590,0.326,0.496,10.0,31.456
4,train,I,0.500,0.395,0.141,0.621,0.292,0.120,0.195,9.0,5.648
5,train,I,0.439,0.335,0.110,0.389,0.175,0.083,0.111,7.0,1.967
6,train,I,0.295,0.220,0.085,0.129,0.058,0.027,0.037,5.0,0.229
7,train,I,0.475,0.365,0.120,0.519,0.268,0.109,0.137,8.0,4.143
8,train,M,0.550,0.451,0.149,1.014,0.408,0.202,0.287,10.0,16.212
9,train,I,0.465,0.355,0.119,0.581,0.255,0.092,0.184,8.0,7.456
10,test,I,0.380,0.290,0.100,0.237,0.108,0.040,0.082,6.0,2.285
11,train,F,0.619,0.475,0.175,1.017,0.436,0.214,0.325,10.0,20.275
12,train,I,0.510,0.399,0.125,0.593,0.239,0.130,0.204,8.0,6.862
13,train,I,0.495,0.381,0.130,0.513,0.218,0.116,0.160,7.0,5.506
14,test,I,0.485,0.390,0.125,0.591,0.287,0.141,0.120,9.0,6.302
15,train,I,0.499,0.380,0.110,0.562,0.280,0.107,0.150,9.0,5.090
16,test,I,0.405,0.310,0.110,0.911,0.416,0.208,0.099,8.0,8.616
17,test,F,0.575,0.470,0.155,1.116,0.510,0.239,0.339,10.0,22.109
18,train,M,0.695,0.549,0.195,1.664,0.727,0.359,0.445,11.0,24.599
19,train,F,0.555,0.430,0.136,0.812,0.405,0.164,0.222,9.0,16.362
20,test,F,0.550,0.425,0.145,0.797,0.297,0.150,0.265,9.0,14.634
21,train,M,0.549,0.421,0.161,1.340,0.633,0.311,0.344,10.0,20.974
22,train,F,0.715,0.524,0.185,1.560,0.665,0.383,0.405,11.0,32.519
23,train,F,0.575,0.475,0.160,0.895,0.360,0.220,0.272,9.0,16.902
24,,,,,,,,,,,
25,,,,,Table 1:,Earshells da,ta example.,,,,

In [14]:
nicer_table_df

,Subset,Sex,Length,Diameter,Height,WholeW.,ShuckedW.,VisceraW.,ShellW.,Rings,Price
1,train,I,0.35,0.26,0.075,0.18,0.09,0.025,0.055,5.0,1.206
2,train,F,0.545,0.44,0.135,0.918,0.429,0.202,0.238,10.0,18.403
3,test,F,0.65,0.545,0.175,1.524,0.59,0.326,0.496,10.0,31.456
4,train,I,0.5,0.395,0.141,0.621,0.292,0.12,0.195,9.0,5.648
5,train,I,0.439,0.335,0.11,0.389,0.175,0.083,0.111,7.0,1.967
6,train,I,0.295,0.22,0.085,0.129,0.058,0.027,0.037,5.0,0.229
7,train,I,0.475,0.365,0.12,0.519,0.268,0.109,0.137,8.0,4.143
8,train,M,0.55,0.451,0.149,1.014,0.408,0.202,0.287,10.0,16.212
9,train,I,0.465,0.355,0.119,0.581,0.255,0.092,0.184,8.0,7.456
10,test,I,0.38,0.29,0.1,0.237,0.108,0.04,0.082,6.0,2.285
11,train,F,0.619,0.475,0.175,1.017,0.436,0.214,0.325,10.0,20.275
12,train,I,0.51,0.399,0.125,0.593,0.239,0.13,0.204,8.0,6.862
13,train,I,0.495,0.381,0.13,0.513,0.218,0.116,0.16,7.0,5.506
14,test,I,0.485,0.39,0.125,0.591,0.287,0.141,0.12,9.0,6.302
15,train,I,0.499,0.38,0.11,0.562,0.28,0.107,0.15,9.0,5.09
16,test,I,0.405,0.31,0.11,0.911,0.416,0.208,0.099,8.0,8.616
17,test,F,0.575,0.47,0.155,1.116,0.51,0.239,0.339,10.0,22.109
18,train,M,0.695,0.549,0.195,1.664,0.727,0.359,0.445,11.0,24.599
19,train,F,0.555,0.43,0.136,0.812,0.405,0.164,0.222,9.0,16.362
20,test,F,0.55,0.425,0.145,0.797,0.297,0.15,0.265,9.0,14.634
21,train,M,0.549,0.421,0.161,1.34,0.633,0.311,0.344,10.0,20.974
22,train,F,0.715,0.524,0.185,1.56,0.665,0.383,0.405,11.0,32.519
23,train,F,0.575,0.475,0.16,0.895,0.36,0.22,0.272,9.0,16.902
Mean,<NA>,<NA>,0.516348,0.403696,0.135696,0.803609,0.354174,0.172522,0.22487,8.608696,12.598043
Std,<NA>,<NA>,0.100507,0.083709,0.030381,0.420805,0.178315,0.099096,0.122374,1.661302,9.424952

***

## Bonus Part IV: Read a table from a PDF by specifying the section

#### This last part is not required to complete assignment 1!

You have probably realised
the table in ```data/A1_table_example.pdf``` is a simplified example. If you consider
the vision transformer paper ```data/A1_ViT_paper.pdf```, you notice that it is more 
challenging to read tables from "real" documents correctly.

In this last section, you can explore how to extract tables in more realistic
scenarios if you are interested.

We load again the "undecorated" function ```get_pandas_df```for this.

In [15]:
def get_pandas_df(page, search_strategy="text", search_region=None):
    tabs = page.find_tables(strategy=search_strategy, clip=search_region)

    tab = tabs[0]
    df = tab.to_pandas()

    df = df.convert_dtypes()

    return df

The additional arguments ```search_strategy``` / ```strategy```  and 
```search_region``` / ```clip``` provide additional control on how and 
where to find tables in the PDF. We focus on ```search_region``` / ```clip``` in the following.
As before, you can find more in the [find_tables documentation](https://pymupdf.readthedocs.io/en/latest/page.html#Page.find_tables).

With ```search_region``` / ```clip```, you can specify a particular region of the 
page that should be parsed.

#### Bonus Exercise IV.1
Explore different settings for ```custom_rectangle``` by changing the arguments of
```fitz.Rect(...)``` and see how well you can parse the tables!

In [16]:
# Bonus Exercise IV.1
# Goal: use a rectangle to tell PyMuPDF where it should search for a table.